(function () {
  "use strict";
  const C = window.RECRUIT_CONTENT, E = window.RecruitEngine;
  const KEYS = { sessions: "ava:recruit:sessions:v2", active: "ava:recruit:active-session:v2", settings: "ava:recruit:user-settings:v2", admin: "ava:recruit:admin-preview:v2" };
  const steps = ["welcome","ideal","rank","employment","current","tradeoff","industry","ava-method","career-tradeoff","path-choice","paths","income-intro","income-input","income-result","career-compare","reflection","complete"];
  const pages = {
    welcome:`<div class="hero-card"><span class="eyebrow">CAREER DISCOVERY</span><h1>先了解你想要嘅工作，<br>再了解保險業。</h1><p>呢個流程唔係要證明你適合。可能適合，亦可能唔適合；重點係將工作內容、可能得到嘅嘢同需要承擔嘅代價一齊看清楚。</p><div class="hero-actions"><button class="primary-button" data-next>開始探索</button><button class="secondary-button" id="resumeButton" hidden>繼續上次進度</button></div></div>`,
    ideal:q("01 · 我的理想工作","如果唔考慮工種，你理想中一份工作最重要係啲乜？","先揀最重要 3 項。選項只係幫你表達自己，冇標準答案。",`<div class="option-grid" id="idealOptions"></div><div class="selection-status" id="idealStatus">已選 0／3</div>`,true,"排列 Top 3"),
    rank:q("01 · 排列優先次序","將三項排成你心目中嘅 Top 1、Top 2、Top 3","點選兩項可以交換位置。",`<div id="rankList" class="rank-list"></div>`,false,"建立「我的理想工作」"),
    employment:q("02 · 現時工作","你而家有冇一份主要工作？","",`<div class="single-options" id="employmentOptions"><button class="choice-card" data-value="employed">有，目前有主要工作</button><button class="choice-card" data-value="not-employed">暫時冇／情況不同</button></div>`,true,"繼續"),
    current:q("02 · 現時工作","你而家份工作，最珍惜佢畀到你啲乜？","只揀 Top 3。完成之前，我哋唔急住談代價。",`<div class="option-grid" id="currentOptions"></div><div class="selection-status" id="currentStatus">已選 0／3</div>`,true,"看看另一面"),
    tradeoff:q("03 · Trade-off Reveal","每一份工作都有佢畀到我哋嘅嘢","好多時，我哋得到一樣嘢，同時亦會用另一樣嘢交換。逐張點擊，睇埋完整一面。",`<div class="reveal-grid" id="tradeoffCards"></div>`,false,"了解另一種工作"),
    industry:q("04 · 真正了解保險業","保險工作，實際服務緊邊啲需要？","工作唔只係介紹一種產品，而係理解個人、家庭、生活及企業面對嘅不同風險。個別產品／服務能否正式提供，仍以公司最新制度及 Admin 核實內容為準。",`<div class="story-grid" id="industryGroups"></div><h3>人生同需要會一路改變</h3><div class="journey" id="lifeJourney"></div><p class="callout">有保單 ≠ 所有需要都已經處理好。專業工作係了解現況 → Review → 分析 → 發現需要 → 呈現差距，再由客戶自己決定。</p>`,false,"睇 AVA 工作方法",true),
    "ava-method":q("04 · AVA 方法","將複雜問題，變成客戶容易理解嘅一步一步","AVA 唔只係 Apps；佢係由現況、目標、數字差距到自主決定嘅工作方法。",`<div class="method-grid" id="methodCards"></div>`,false,"了解保險事業嘅兩面",true),
    "career-tradeoff":q("05 · 得到 × 代價","保險事業都要用同一把尺去看","唔只講可能得到嘅嘢，亦同時睇背後需要承擔嘅要求。",`<div class="comparison-grid" id="careerTradeoffs"></div>`,false,"睇如何開始",true),
    "path-choice":q("06 · 如何開始","如果你覺得呢個行業有值得了解嘅地方，你比較想用咩方式探索？","",`<div class="single-options" id="pathOptions"><button class="choice-card" data-value="flexible"><strong>漸進發展／Flexible Path</strong><small>保留主要收入來源，邊學習、邊體驗，再決定下一步。</small></button><button class="choice-card" data-value="fulltime"><strong>全力發展／Full-time Path</strong><small>將主要時間投入專業、客戶基礎及事業發展。</small></button><button class="choice-card" data-value="unknown"><strong>我仲未知道</strong><small>先用相同框架比較兩種模式。</small></button></div>`,true,"比較 Career Path"),
    paths:q("06 · 雙 Career Path","兩種投入方式，冇高低之分","",`<div class="path-grid" id="pathCards"></div><div id="availabilityPanel" class="availability-panel" hidden><h3>Flexible Path 現實時間盤點</h3><div class="field-grid"><label>每星期可投入時間<input id="hoursInput" type="number" min="0" max="80" inputmode="numeric" placeholder="例如 8"></label><label>平日晚間<select id="eveningInput"><option value="">請選擇</option><option>大部分可以</option><option>部分日子可以</option><option>較難安排</option></select></label><label>週末<select id="weekendInput"><option value="">請選擇</option><option>大部分可以</option><option>部分時間可以</option><option>較難安排</option></select></label><label>個人／家庭限制<input id="constraintInput" maxlength="120" placeholder="可選填"></label></div><div class="mini-timeline">${["現在","探索期","學習","建立基礎","評估點","再決定"].map(x=>`<span>${x}</span>`).join("")}</div></div>`,false,"了解收入模式",true),
    "income-intro":q("07 · Income Simulator","收入由邊度形成？","",`<div class="income-formula"><span>個人業務</span><b>＋</b><span>適用津貼</span><b>＋</b><span>持續發展收入</span><b>＋</b><span>適用獎勵／管理發展</span></div><p class="disclaimer">具體項目按現有正式 Recruit Engine、所選計劃及輸入假設計算。模擬結果並非收入保證。</p>`,false,"建立簡單情境"),
    "income-input":q("07 · Simple Scenario","先建立第 1 年情境","預設唔放入任何收入假設，由你按實際情況輸入；如要保留原有逐年控制，可展開 7 年詳細設定。",`<div class="sim-grid"><label>Recruitment Package<select id="packageInput"></select></label><label>目標每月津貼（MB）<select id="mbInput"></select></label><label>醫療保費<input id="medInput" inputmode="numeric" value="0"></label><label>危疾保費<input id="ciInput" inputmode="numeric" value="0"></label><label>儲蓄保費<input id="savInput" inputmode="numeric" value="0"></label></div><div id="requirementSummary" class="callout"></div><div class="check-row"><label><input id="continuousInput" type="checkbox"> 連續 MDRT 額外花紅</label><label><input id="excellentInput" type="checkbox"> 卓越顧問花紅</label></div><details id="yearEditor"><summary>查看／設定 7 年詳細業務</summary><div class="table-wrap"><table><thead><tr><th>年份</th><th>醫療</th><th>危疾</th><th>儲蓄</th></tr></thead><tbody id="yearInputs"></tbody></table></div></details>`,false,"計算情境",true),
    "income-result":q("07 · 模擬結果 × 形成條件","結果同要求，要一齊睇","按目前輸入及假設計算的模擬結果，並非收入保證。",`<div id="incomeSummary" class="summary-grid"></div><div id="incomeRequirements" class="callout"></div><button class="text-button" id="longViewButton">睇現有正式 7 年預測期</button><div id="longView" hidden><div class="chart" id="incomeChart"></div><details><summary>查看詳細計算</summary><div class="table-wrap"><table><thead><tr><th>年份</th><th>FYC</th><th>MB</th><th>YEB</th><th>MDRT</th><th>續保</th><th>總收入</th><th>累積</th></tr></thead><tbody id="incomeTable"></tbody></table></div></details></div>`,false,"比較 Career Path",true,"修改情境"),
    "career-compare":q("08 · Career Path Comparison","唔只比較人工，亦比較發展結構","",`<div class="salary-inputs"><label>目前月薪<input id="salaryInput" type="number" min="0" inputmode="numeric" placeholder="可選填"></label><label>每年薪酬增長假設 %<input id="growthInput" type="number" min="-100" max="100" step="0.1" value="0"></label><label>每年 Bonus（月數）<input id="bonusInput" type="number" min="0" max="24" step="0.1" value="0"></label></div><div id="careerComparison" class="career-comparison"></div><p class="disclaimer">非量化項目只以 Milestone／Trade-off 描述，不設虛假分數。保險職級名稱只採用現有正式資料已列出的 AUM；其他階段使用工作里程碑描述。</p>`,false,"最後整理",true),
    reflection:q("09 · Reflection","回到你最重視嘅三樣嘢","",`<div id="idealRecap" class="rank-list compact"></div><div id="reflectionFrame" class="reflection-frame"></div><h3>睇完之後，你覺得邊一部分最值得再了解？</h3><div class="option-grid" id="reflectionOptions"></div>`,false,"保存今次探索",true),
    complete:`<div class="hero-card"><span class="eyebrow">REFLECTION SAVED</span><h1>可能適合，亦可能唔適合。</h1><p>你已經保存今次探索。下次可以由目前進度繼續，亦可以切換 Flexible／Full-time Path，前面嘅理想工作與現職資料會保留。</p><div class="hero-actions"><button class="primary-button" id="reviewButton">查看我的整理</button><button class="secondary-button" id="newSessionButton">建立另一個 Session</button></div></div>`
  };
  function q(label,title,support,body,disabled,next,wide,back="返回"){return `<div class="question-card${wide?" wide":""}"><span class="step-label">${label}</span><h2>${title}</h2>${support?`<p>${support}</p>`:""}${body}<div class="flow-actions"><button class="secondary-button" data-back>${back}</button><button class="primary-button" data-next ${disabled?"disabled":""}>${next}</button></div></div>`}
  const shell=document.getElementById("flowShell"); shell.innerHTML=steps.map(s=>`<section class="flow-page" data-step="${s}">${pages[s]}</section>`).join("");
  let sessions=read(KEYS.sessions,[]), activeId=localStorage.getItem(KEYS.active), mode="recruiter", step="welcome", rankPick=null, result=null;
  let state=fresh();
  function fresh(){return {id:`candidate-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,name:"Candidate",updatedAt:new Date().toISOString(),step:"welcome",ideal:[],employment:"",current:[],path:"",availability:{},income:{packageId:"PA18",mbAmount:10000,years:Array.from({length:7},()=>({med:0,ci:0,sav:0})),continuousMdrt:false,excellentAgent:false},salary:{monthly:0,growth:0,bonus:0},reflection:[]}}
  function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
  function save(show=false){state.step=step;state.updatedAt=new Date().toISOString();const at=sessions.findIndex(s=>s.id===state.id);if(at>=0)sessions[at]=state;else sessions.unshift(state);localStorage.setItem(KEYS.sessions,JSON.stringify(sessions));localStorage.setItem(KEYS.active,state.id);activeId=state.id;if(show)toast("進度已保存喺呢部裝置")}
  function escape(s){const d=document.createElement("div");d.textContent=String(s??"");return d.innerHTML}
  function money(n){return "$"+Math.round(Number(n)||0).toLocaleString("en-US")}
  function go(target){if(!steps.includes(target))return;step=target;document.querySelectorAll(".flow-page").forEach(p=>p.classList.toggle("active",p.dataset.step===step));document.getElementById("progressFill").style.width=`${Math.max(0,steps.indexOf(step))/(steps.length-2)*100}%`;render();save();window.scrollTo({top:0,behavior:"smooth"})}
  function next(){let i=steps.indexOf(step);if(step==="employment"&&state.employment!=="employed")i=steps.indexOf("tradeoff")-1;if(step==="income-input")compute();go(steps[Math.min(i+1,steps.length-1)])}
  function back(){let i=steps.indexOf(step);if(step==="tradeoff"&&state.employment!=="employed")i=steps.indexOf("employment")+1;go(steps[Math.max(i-1,0)])}
  function optionButtons(items,selected){return items.map(x=>`<button class="option${selected.includes(x)?" selected":""}" data-value="${escape(x)}">${escape(x)}</button>`).join("")}
  function render(){
    if(step==="welcome"){const b=document.getElementById("resumeButton");b.hidden=!activeId;b.onclick=()=>{const s=sessions.find(x=>x.id===activeId);if(s){state=s;go(s.step==="complete"?"reflection":s.step)}}}
    if(step==="ideal")renderMulti("idealOptions",C.idealValues,state.ideal,"idealStatus");
    if(step==="rank"){document.getElementById("rankList").innerHTML=state.ideal.map((x,i)=>`<button class="rank-item${rankPick===i?" selected":""}" data-rank="${i}"><span class="rank-number">Top ${i+1}</span><strong>${escape(x)}</strong></button>`).join("")}
    if(step==="employment")renderSingle("employmentOptions",state.employment);
    if(step==="current")renderMulti("currentOptions",C.currentValues,state.current,"currentStatus");
    if(step==="tradeoff"){const values=state.current.length?state.current:state.ideal;document.getElementById("tradeoffCards").innerHTML=values.map(x=>{const t=C.tradeoffs[x]||["呢項價值對你有實際意義。","維持任何工作價值，都需要相應投入及限制。"] ;return `<article class="reveal-card"><button><strong>你得到的是：${escape(x)}</strong><p>${escape(t[0])}</p><small>點擊 Reveal</small></button><div class="tradeoff"><strong>背後可能伴隨的是：</strong><p>${escape(t[1])}</p></div></article>`}).join("")}
    if(step==="industry"){document.getElementById("industryGroups").innerHTML=C.industryGroups.map(g=>`<article class="story-card"><h3>${g.title}</h3><ul>${g.items.map(x=>`<li>${x}</li>`).join("")}</ul></article>`).join("");document.getElementById("lifeJourney").innerHTML=C.lifeJourney.map(x=>`<span>${x}</span>`).join("")}
    if(step==="ava-method")document.getElementById("methodCards").innerHTML=C.avaMethods.map(x=>`<article class="method-card"><h3>${x.title}</h3><p>${x.text}</p><a href="${x.url}" target="_blank" rel="noopener">開啟獨立 AVA Module ↗</a></article>`).join("");
    if(step==="career-tradeoff")document.getElementById("careerTradeoffs").innerHTML=C.careerTradeoffs.map(x=>`<article class="comparison-card"><h3>${x[0]}</h3><p class="gain"><strong>可能得到：</strong><br>${x[1]}</p><p class="cost"><strong>需要承擔：</strong><br>${x[2]}</p></article>`).join("");
    if(step==="path-choice")renderSingle("pathOptions",state.path);
    if(step==="paths")renderPaths();
    if(step==="income-input")renderIncomeInput();
    if(step==="income-result")renderIncomeResult();
    if(step==="career-compare")renderCareer();
    if(step==="reflection")renderReflection();
    bindPage();
  }
  function renderMulti(id,items,selected,statusId){const box=document.getElementById(id);box.innerHTML=optionButtons(items,selected);document.getElementById(statusId).textContent=`已選 ${selected.length}／3`;document.querySelector(`[data-step="${step}"] [data-next]`).disabled=selected.length!==3;box.querySelectorAll(".option").forEach(b=>b.onclick=()=>{const v=b.dataset.value,i=selected.indexOf(v);if(i>=0)selected.splice(i,1);else if(selected.length<3)selected.push(v);render();save()})}
  function renderSingle(id,value){const box=document.getElementById(id);box.querySelectorAll("[data-value]").forEach(b=>{b.classList.toggle("selected",b.dataset.value===value);b.onclick=()=>{if(id==="employmentOptions")state.employment=b.dataset.value;else state.path=b.dataset.value;render();save()}});document.querySelector(`[data-step="${step}"] [data-next]`).disabled=!value}
  function renderPaths(){document.getElementById("pathCards").innerHTML=Object.entries(C.paths).map(([id,p])=>`<article class="path-card${state.path===id?" active":""}"><h3>${p.title}</h3><p>${p.intro}</p><div class="two-sides"><div><strong>可能得到</strong><ul>${p.gets.map(x=>`<li>${x}</li>`).join("")}</ul></div><div><strong>需要交換</strong><ul>${p.costs.map(x=>`<li>${x}</li>`).join("")}</ul></div></div><button class="secondary-button full" data-path-switch="${id}">查看呢條 Path</button></article>`).join("");const panel=document.getElementById("availabilityPanel");panel.hidden=state.path==="fulltime";["hours","evening","weekend","constraint"].forEach(k=>{const el=document.getElementById(k+"Input");if(el){el.value=state.availability[k]||"";el.onchange=()=>{state.availability[k]=el.value;save()}}})}
  function renderIncomeInput(){const p=document.getElementById("packageInput");p.innerHTML=Object.keys(E.MB_OPTIONS).map(x=>`<option>${x}</option>`).join("");p.value=state.income.packageId;p.onchange=()=>{state.income.packageId=p.value;state.income.mbAmount=E.MB_OPTIONS[p.value][0];renderIncomeInput();save()};const mb=document.getElementById("mbInput");mb.innerHTML=E.MB_OPTIONS[p.value].map(x=>`<option value="${x}">${money(x)}</option>`).join("");mb.value=state.income.mbAmount;mb.onchange=()=>{state.income.mbAmount=Number(mb.value);requirements();save()};[["medInput","med"],["ciInput","ci"],["savInput","sav"]].forEach(([id,k])=>{const el=document.getElementById(id);el.value=state.income.years[0][k];el.oninput=()=>{state.income.years[0][k]=Number(el.value.replace(/\D/g,""))||0;requirements();save()}});[["continuousInput","continuousMdrt"],["excellentInput","excellentAgent"]].forEach(([id,k])=>{const el=document.getElementById(id);el.checked=state.income[k];el.onchange=()=>{state.income[k]=el.checked;save()}});const rows=document.getElementById("yearInputs");rows.innerHTML=state.income.years.map((y,i)=>`<tr><td>第 ${i+1} 年</td>${["med","ci","sav"].map(k=>`<td><input data-year="${i}" data-kind="${k}" inputmode="numeric" value="${y[k]||0}" aria-label="第 ${i+1} 年 ${k}"></td>`).join("")}</tr>`).join("");rows.querySelectorAll("input").forEach(el=>el.oninput=()=>{const y=Number(el.dataset.year),k=el.dataset.kind;state.income.years[y][k]=Number(el.value.replace(/\D/g,""))||0;if(y===0){document.getElementById(k==="med"?"medInput":k==="ci"?"ciInput":"savInput").value=state.income.years[y][k]}save()});requirements()}
  function requirements(){const p=state.income.packageId,mb=state.income.mbAmount;document.getElementById("requirementSummary").innerHTML=`<strong>${p} 形成條件</strong><br>${C.packages[p].matching}<br>目前所選 MB：${money(mb)}。<br><small>入職資格：${C.packages[p].qualification}</small>`}
  function compute(){const first={...state.income.years[0]};state.income.years=state.income.years.map((x,i)=>i===0?first:((x.med||x.ci||x.sav)?x:{...first}));result=E.calculate(state.income);save()}
  function renderIncomeResult(){if(!result)compute();const y=result.yearly[1],renew=y.rc+y.renewalBonus;document.getElementById("incomeSummary").innerHTML=[["第 1 年模擬總收入",y.total],["個人業務 FYC",y.fyc],["適用津貼 MB",y.mb],["獎勵及續保",y.yeb+y.mdrt+renew]].map(x=>`<article class="summary-card"><span>${x[0]}</span><strong>${money(x[1])}</strong></article>`).join("");const inputs=state.income.years[0];document.getElementById("incomeRequirements").innerHTML=`<strong>形成呢個結果嘅輸入及條件</strong><br>醫療 ${money(inputs.med)} ／ 危疾 ${money(inputs.ci)} ／ 儲蓄 ${money(inputs.sav)}；按正式權重形成 FYC ${money(y.fyc)}。${C.packages[state.income.packageId].matching}`;const max=Math.max(...result.yearly.slice(1).map(x=>x.total),1);document.getElementById("incomeChart").innerHTML=result.yearly.slice(1).map((x,i)=>`<div class="bar-wrap"><small>${money(x.total)}</small><div class="bar" style="height:${x.total/max*170}px"></div><span>Y${i+1}</span></div>`).join("");document.getElementById("incomeTable").innerHTML=result.yearly.slice(1).map((x,i)=>`<tr><td>第 ${i+1} 年</td>${[x.fyc,x.mb,x.yeb,x.mdrt,x.rc+x.renewalBonus,x.total,x.cumulative].map(n=>`<td>${money(n)}</td>`).join("")}</tr>`).join("");document.getElementById("longViewButton").onclick=()=>document.getElementById("longView").hidden=!document.getElementById("longView").hidden}
  function renderCareer(){if(!result)compute();const salary=state.salary.monthly||0,g=state.salary.growth/100,b=state.salary.bonus;const employed=n=>salary*Math.pow(1+g,n-1)*(12+b);document.getElementById("careerComparison").innerHTML=`<article class="career-column"><h3>目前工作</h3><p><strong>Today</strong><br>${salary?money(employed(1))+"／年":"可輸入目前月薪"}</p><p><strong>2 Years</strong><br>${salary?money(employed(2))+"／年":"按現職制度發展"}</p><p><strong>5 Years</strong><br>${salary?money(employed(5))+"／年":"按現職制度發展"}</p><small>較穩定收入結構；時間、晉升及福利受僱傭制度影響。</small></article><article class="career-column"><h3>Flexible Path</h3><p><strong>探索</strong><br>保留主要收入來源</p><p><strong>建立基礎</strong><br>學習、客戶服務與活動並行</p><p><strong>評估點</strong><br>維持／增加投入／全職／停止</p><small>投入較少、速度可能較慢，需要同時管理兩邊時間。</small></article><article class="career-column"><h3>Full-time Path</h3><p><strong>New Agent</strong><br>集中建立專業與客戶基礎</p><p><strong>個人業務</strong><br>發展穩定活動及服務</p><p><strong>Management</strong><br>符合正式要求後可探索 AUM／團隊發展</p><small>第 1 年模擬：${money(result.yearly[1].total)}；收入會波動，並非保證。</small></article>`;[["salaryInput","monthly"],["growthInput","growth"],["bonusInput","bonus"]].forEach(([id,k])=>{const el=document.getElementById(id);el.value=state.salary[k]||0;el.oninput=()=>{state.salary[k]=Number(el.value)||0;renderCareer();save()}})}
  function renderReflection(){document.getElementById("idealRecap").innerHTML=state.ideal.map((x,i)=>`<div class="rank-item"><span class="rank-number">Top ${i+1}</span><strong>${escape(x)}</strong></div>`).join("");document.getElementById("reflectionFrame").innerHTML=`<div><strong>目前工作</strong><p>以你現時得到嘅價值、制度與相應 Trade-off 作判斷。</p></div><div><strong>Flexible Path</strong><p>保留主要收入來源，透過探索期實際驗證。</p></div><div><strong>Full-time Path</strong><p>集中投入，同時承擔收入波動及轉職壓力。</p></div>`;document.getElementById("reflectionOptions").innerHTML=optionButtons(C.reflectionOptions,state.reflection);document.querySelectorAll("#reflectionOptions .option").forEach(b=>b.onclick=()=>{const i=state.reflection.indexOf(b.dataset.value);i>=0?state.reflection.splice(i,1):state.reflection.push(b.dataset.value);renderReflection();save()})}
  function bindPage(){document.querySelectorAll(`[data-step="${step}"] [data-next]`).forEach(b=>b.onclick=next);document.querySelectorAll(`[data-step="${step}"] [data-back]`).forEach(b=>b.onclick=back);document.querySelectorAll(".reveal-card button").forEach(b=>b.onclick=()=>b.parentElement.classList.toggle("revealed"));document.querySelectorAll("[data-rank]").forEach(b=>b.onclick=()=>{const i=Number(b.dataset.rank);if(rankPick===null)rankPick=i;else{[state.ideal[rankPick],state.ideal[i]]=[state.ideal[i],state.ideal[rankPick]];rankPick=null;save()}render()});document.querySelectorAll("[data-path-switch]").forEach(b=>b.onclick=()=>{state.path=b.dataset.pathSwitch;renderPaths();save()});const review=document.getElementById("reviewButton");if(review)review.onclick=()=>go("reflection");const newer=document.getElementById("newSessionButton");if(newer)newer.onclick=newSession}
  function openDrawer(id){document.getElementById("drawerBackdrop").hidden=false;document.getElementById(id).classList.add("open");document.getElementById(id).setAttribute("aria-hidden","false");if(id==="sessionDrawer")renderSessions()}
  function closeDrawers(){document.getElementById("drawerBackdrop").hidden=true;document.querySelectorAll(".drawer").forEach(x=>{x.classList.remove("open");x.setAttribute("aria-hidden","true")})}
  function renderSessions(){const box=document.getElementById("sessionList");box.innerHTML=sessions.map(s=>`<article class="session-card"><strong>${escape(s.name||"Candidate")}</strong><small>${new Date(s.updatedAt).toLocaleString("zh-HK")} · ${escape(s.step)}</small><div class="session-actions"><button data-load="${s.id}">繼續</button><button data-rename="${s.id}">改名</button><button data-delete="${s.id}">刪除</button></div></article>`).join("")||"<p>未有已保存 Session。</p>";box.querySelectorAll("[data-load]").forEach(b=>b.onclick=()=>{state=sessions.find(s=>s.id===b.dataset.load);activeId=state.id;closeDrawers();go(state.step)});box.querySelectorAll("[data-rename]").forEach(b=>b.onclick=()=>{const s=sessions.find(x=>x.id===b.dataset.rename),n=prompt("Session 名稱",s.name);if(n){s.name=n.trim().slice(0,50)||s.name;save();renderSessions()}});box.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>{if(confirm("刪除呢個本機 Session？")){sessions=sessions.filter(s=>s.id!==b.dataset.delete);localStorage.setItem(KEYS.sessions,JSON.stringify(sessions));renderSessions()}})}
  function newSession(){state=fresh();result=null;activeId=state.id;save();closeDrawers();go("welcome")}
  function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
  document.getElementById("modeButton").onclick=()=>{mode=mode==="recruiter"?"candidate":"recruiter";document.getElementById("modeButton").textContent=mode==="recruiter"?"Recruiter Mode":"Candidate Mode";toast(mode==="recruiter"?"適合 iPad 面對面逐步講解":"內容改以自行探索方式顯示")};document.getElementById("sessionsButton").onclick=()=>openDrawer("sessionDrawer");document.getElementById("settingsButton").onclick=()=>openDrawer("settingsDrawer");document.getElementById("drawerBackdrop").onclick=closeDrawers;document.querySelectorAll(".drawer-close").forEach(b=>b.onclick=closeDrawers);document.getElementById("addSessionButton").onclick=newSession;
  document.querySelectorAll("[data-settings-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-settings-tab]").forEach(x=>x.classList.toggle("active",x===b));document.getElementById("userSettings").hidden=b.dataset.settingsTab!=="user";document.getElementById("adminSettings").hidden=b.dataset.settingsTab!=="admin"});
  const userSettings=read(KEYS.settings,{themeName:C.theme.name,defaultMode:"recruiter"});document.getElementById("brandName").textContent=userSettings.themeName;document.getElementById("themeNameInput").value=userSettings.themeName;document.getElementById("defaultModeInput").value=userSettings.defaultMode;mode=userSettings.defaultMode;document.getElementById("modeButton").textContent=mode==="recruiter"?"Recruiter Mode":"Candidate Mode";document.getElementById("versionText").textContent=C.version;
  document.getElementById("saveUserSettings").onclick=()=>{const x={themeName:document.getElementById("themeNameInput").value.trim()||C.theme.name,defaultMode:document.getElementById("defaultModeInput").value};localStorage.setItem(KEYS.settings,JSON.stringify(x));document.getElementById("brandName").textContent=x.themeName;toast("個人設定已保存")};document.getElementById("resetUserSettings").onclick=()=>{localStorage.removeItem(KEYS.settings);document.getElementById("brandName").textContent=C.theme.name;document.getElementById("themeNameInput").value=C.theme.name;toast("已恢復系統預設")};
  document.getElementById("exportButton").onclick=()=>{const blob=new Blob([JSON.stringify({type:"ava-recruit-backup",version:C.version,sessions},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="ava-recruit-backup.json";a.click();URL.revokeObjectURL(a.href)};document.getElementById("importInput").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.type!=="ava-recruit-backup"||!Array.isArray(d.sessions))throw Error();sessions=d.sessions;localStorage.setItem(KEYS.sessions,JSON.stringify(sessions));toast("Sessions 已匯入")}catch{toast("備份檔案格式不正確")}};r.readAsText(f)};
  document.getElementById("unlockAdminButton").onclick=()=>{if(document.getElementById("adminCodeInput").value!=="8888"){toast("Access Code 不正確");return}document.getElementById("adminEditor").hidden=false;const a=read(KEYS.admin,{copy:"可能適合，亦可能唔適合。",version:C.version});document.getElementById("adminCopyInput").value=a.copy;document.getElementById("contentVersionInput").value=a.version};document.getElementById("saveAdminPreview").onclick=()=>{localStorage.setItem(KEYS.admin,JSON.stringify({copy:document.getElementById("adminCopyInput").value,version:document.getElementById("contentVersionInput").value}));toast("Admin 本機預覽已保存")};
  let worker;if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").then(reg=>reg.addEventListener("updatefound",()=>{worker=reg.installing;worker.addEventListener("statechange",()=>{if(worker.state==="installed"&&navigator.serviceWorker.controller)document.getElementById("updateBanner").hidden=false})})).catch(()=>{}));document.getElementById("updateButton").onclick=()=>worker&&worker.postMessage({action:"skipWaiting"});
  if(activeId){const found=sessions.find(s=>s.id===activeId);if(found)state=found}render();go("welcome");
  const avaEntry=new URLSearchParams(window.location.search).get("avaEntry");
  if(["frontend","user","admin"].includes(avaEntry)){
    const returnButton=document.getElementById("avaReturnButton");
    returnButton.hidden=false;
    returnButton.href=avaEntry==="frontend"?"https://ivancww.github.io/avaplatform/":`https://ivancww.github.io/avaplatform/?avaSurface=${avaEntry}`;
    if(avaEntry==="user") openDrawer("settingsDrawer");
    if(avaEntry==="admin"){
      document.querySelector('[data-settings-tab="admin"]').click();
      openDrawer("settingsDrawer");
    }
  }
})();
